Repository pocketnetteam/pocketnet.core, pull requests merged in 2023-02, with the labels that each got.

#534 feat: Create BlockChainBuilder & helper functions for the functional tests
  test/functional/pocketnet/account_delete.py
  test/functional/pocketnet/badges.py
  test/functional/pocketnet/content_collections.py
  test/functional/pocketnet/framework/chain_builder.py
  test/functional/pocketnet/framework/helpers.py
  test/functional/pocketnet/framework/models.py
  test/functional/pocketnet/moderation_jury.py
  test/functional/pocketnet/moderation_jury_no_ban.py
Labels: feature, tests

#542 feature: Introduce Pocketnet test runner
  contrib/install_db4.sh
  test/functional/pocketnet/README.md
  test/functional/pocketnet/__init__.py
  test/functional/pocketnet/chainbuilder_full_activity.py
  test/functional/pocketnet/pyproject.toml
  test/functional/pocketnet/test_runner.py
Labels: feature, tests

#545 fix: moderation api
  src/init.cpp
  src/pocketdb/SQLiteConnection.cpp
  src/pocketdb/SQLiteDatabase.cpp
  src/pocketdb/repositories/BaseRepository.h
  src/pocketdb/repositories/ChainRepository.h
  src/pocketdb/repositories/ConsensusRepository.cpp
  src/pocketdb/repositories/ConsensusRepository.h
  src/pocketdb/repositories/MigrationRepository.h
  src/pocketdb/repositories/RatingsRepository.h
  src/pocketdb/repositories/SystemRepository.h
  src/pocketdb/repositories/TransactionRepository.h
  src/pocketdb/repositories/web/ModerationRepository.cpp
Labels: bug, feature

#548 feature: Feeds functional tests
  test/functional/pocketnet/chainbuilder_full_activity.py
  test/functional/pocketnet/feeds.py
  test/functional/pocketnet/framework/chain_builder.py
  test/functional/pocketnet/framework/helpers.py
Labels: feature, tests

#551 feature: content functional tests
  test/functional/pocketnet/content_collections.py
  test/functional/pocketnet/contents.py
  test/functional/pocketnet/framework/helpers.py
  test/functional/pocketnet/framework/models.py
Labels: feature, tests

#549 Featute/newapimethod
  src/pocketdb/repositories/web/WebRpcRepository.cpp
  src/pocketdb/repositories/web/WebRpcRepository.h
  src/pocketdb/web/PocketContentRpc.cpp
  src/pocketdb/web/PocketContentRpc.h
  src/pocketdb/web/PocketRpc.cpp
Labels: feature

#555 Fixed collection deserializing.
  src/pocketdb/models/dto/content/Collection.cpp
Labels: bug

#559 feature: comments functional tests
  test/functional/pocketnet/comments.py
  test/functional/pocketnet/contents.py
  test/functional/pocketnet/framework/helpers.py
Labels: feature, tests
