Repository pocketnetteam/pocketnet.core, pull requests merged in 2023-01, with the labels that each got.

#519 seeds: request new seeds (#516 #518)
  contrib/seeds/nodes_main.txt
  src/chainparamsseeds.h
Labels: seeds

#520 test: account delete
  src/chainparams.cpp
  src/pocketdb/consensus/Base.h
  src/pocketdb/consensus/Helper.cpp
  src/pocketdb/consensus/moderation/Flag.hpp
  src/pocketdb/consensus/social/Blocking.hpp
  src/pocketdb/models/base/PocketTypes.h
  src/pocketdb/repositories/web/WebRpcRepository.cpp
  src/pocketdb/repositories/web/WebRpcRepository.h
  src/pocketdb/web/PocketAccountRpc.cpp
  src/pocketdb/web/PocketRpc.cpp
  src/pocketdb/web/PocketTransactionRpc.cpp
  src/rpc/mining.cpp
  src/staker.cpp
  src/staker.h
  src/wallet/wallet.cpp
  test/functional/pocketnet/README.md
  test/functional/pocketnet/account_delete.py
  test/functional/pocketnet/framework/__init__.py
  test/functional/pocketnet/framework/models.py
  test/functional/rpc_bind.py
  test/functional/test-shell.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/test_node.py
  test/functional/test_framework/util.py
Labels: tests

#521 feat: subscribes and subscribers rpc methods
  src/pocketdb/repositories/web/WebRpcRepository.cpp
  src/pocketdb/repositories/web/WebRpcRepository.h
  src/pocketdb/web/PocketAccountRpc.cpp
  src/pocketdb/web/PocketRpc.cpp
Labels: feature

#524 seeds: add new fixed node ip by Issue #487
  contrib/seeds/nodes_main.txt
  src/chainparamsseeds.h
Labels: seeds

#522 docs: build-osx.md add openssl configuration
  doc/build-osx.md
Labels: documentation

#511 Added collections of contents
  src/CMakeLists.txt
  src/Makefile.am
  src/pocketdb/consensus/Base.h
  src/pocketdb/consensus/Helper.cpp
  src/pocketdb/consensus/Helper.h
  src/pocketdb/consensus/social/Collection.hpp
  src/pocketdb/consensus/social/ContentDelete.hpp
  src/pocketdb/helpers/TransactionHelper.cpp
  src/pocketdb/helpers/TransactionHelper.h
  src/pocketdb/models/base/PocketTypes.h
  src/pocketdb/models/dto/content/Collection.cpp
  src/pocketdb/models/dto/content/Collection.h
  src/pocketdb/repositories/ChainRepository.cpp
  src/pocketdb/repositories/ConsensusRepository.cpp
  src/pocketdb/repositories/ConsensusRepository.h
  src/pocketdb/repositories/web/WebRpcRepository.cpp
  src/pocketdb/repositories/web/WebRpcRepository.h
  src/pocketdb/web/PocketContentRpc.cpp
  src/pocketdb/web/PocketContentRpc.h
  src/pocketdb/web/PocketRpc.cpp
  test/functional/pocketnet/content_collections.py
  test/functional/pocketnet/framework/models.py
Labels: feature
